/**
 * build.mjs — produce the deployable artifact in dist/.
 *
 * WHY dist/ AND NOT THE REPO ROOT: publishing the root would put
 * `migration/csv/` on the public internet — that directory holds the farm's
 * exported production data. It would also expose the migration SQL, the test
 * suite and package.json. An allow-list of what ships is the only safe default;
 * a deny-list is one forgotten entry away from a leak.
 *
 * Two other jobs:
 *
 *  - Copy `BSF Production Log.dc.html` to `index.html`. The authored filename is
 *    kept because the DC runtime derives component identity from it
 *    (support.js:75) and because it round-trips with Claude Design; index.html
 *    is what gets served, so the PWA start_url has no %20 in it.
 *
 *  - Generate the service worker's precache list by SCANNING the output rather
 *    than from a hand-written list. A hand-maintained list is how an app stays
 *    "offline-capable" right up until someone adds a module and nobody notices
 *    it was never cached.
 */
import { readFile, writeFile, readdir, stat, mkdir, cp, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');
const p = (...s) => path.join(ROOT, ...s);
const d = (...s) => path.join(DIST, ...s);

export const SOURCE_HTML = 'BSF Production Log.dc.html';

/** Explicit allow-list. Nothing reaches dist/ that is not named here. */
const COPY_FILES = [
  ['support.js', 'support.js'],
  ['dataClient.js', 'dataClient.js'],
  ['app-config.js', 'app-config.js'],
  ['manifest.webmanifest', 'manifest.webmanifest'],
  ['sw.js', 'sw.js']
];
const COPY_DIRS = ['src', 'vendor', 'fonts', 'img'];

/** Precached so a cold launch with the radio off renders exactly as online. */
const EXTRA_PRECACHE = [
  './',
  './index.html',
  './support.js',
  './dataClient.js',
  './app-config.js',
  './manifest.webmanifest'
];
const SKIP_EXT = new Set(['.map', '.md']);

async function walk(dir, out = []) {
  let entries;
  try { entries = await readdir(dir, { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) await walk(full, out);
    else if (!SKIP_EXT.has(path.extname(e.name))) out.push(full);
  }
  return out;
}

const toUrl = abs => './' + path.relative(DIST, abs).split(path.sep).join('/');

async function main() {
  if (!existsSync(p(SOURCE_HTML))) throw new Error(`no se encontró "${SOURCE_HTML}"`);
  if (!existsSync(p('vendor', 'react.production.min.js'))) {
    throw new Error('vendor/ está vacío — corre `npm run vendor` primero');
  }

  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });

  await cp(p(SOURCE_HTML), d('index.html'));
  for (const [from, to] of COPY_FILES) await cp(p(from), d(to));
  for (const dir of COPY_DIRS) await cp(p(dir), d(dir), { recursive: true });
  console.log(`  copy    index.html + ${COPY_FILES.length} files + ${COPY_DIRS.length} dirs`);

  const found = [];
  for (const dir of COPY_DIRS) found.push(...await walk(d(dir)));
  const urls = [...new Set([...EXTRA_PRECACHE, ...found.map(toUrl)])].sort();

  // Version = hash of contents, so a rebuild with no changes keeps the same
  // cache and devices do not re-download the whole shell for nothing.
  const hash = createHash('sha256');
  for (const url of urls) {
    if (url === './') continue;
    try { hash.update(url); hash.update(await readFile(d(url.replace(/^\.\//, '')))); } catch { /* generated below */ }
  }
  const version = hash.digest('hex').slice(0, 12);

  await writeFile(
    d('sw-precache.js'),
    `// GENERATED by tools/build.mjs — do not edit.\n` +
    `self.__VERSION = ${JSON.stringify(version)};\n` +
    `self.__PRECACHE = ${JSON.stringify(urls, null, 2)};\n`,
    'utf8'
  );

  // Netlify reads _headers/_redirects from the publish directory. Keeping them
  // in netlify.toml as well is harmless; these make `netlify deploy --dir=dist`
  // and drag-and-drop deploys behave identically to a git-triggered build.
  if (existsSync(p('netlify', '_headers'))) await cp(p('netlify', '_headers'), d('_headers'));
  if (existsSync(p('netlify', '_redirects'))) await cp(p('netlify', '_redirects'), d('_redirects'));

  let bytes = 0;
  for (const url of urls) {
    if (url === './') continue;
    try { bytes += (await stat(d(url.replace(/^\.\//, '')))).size; } catch { /* ignore */ }
  }

  console.log(`  sw      ${urls.length} assets precached, ${(bytes / 1024).toFixed(0)} KB, version ${version}`);

  // A leak here would be production data on the public internet, so assert it
  // rather than trusting the allow-list stayed correct.
  const leaked = (await walk(DIST)).map(f => path.relative(DIST, f))
    .filter(f => /^(migration|supabase|test|tools|node_modules)[\\/]/.test(f) || /\.(csv|sql)$/i.test(f));
  if (leaked.length) throw new Error(`dist/ contiene archivos que no deben publicarse:\n  ${leaked.join('\n  ')}`);
  console.log('  check   no migration data, SQL or tooling in dist/');

  console.log(`\ndist/ listo para publicar.`);
}

main().catch(e => { console.error('build failed:', e.message); process.exitCode = 1; });
