/**
 * vendor.mjs — copy runtime dependencies out of node_modules into committed,
 * self-hosted assets.
 *
 * WHY THIS EXISTS: the app must boot with no network. `support.js` fetches React
 * from unpkg and the page fetched Inter/IBM Plex Mono from fonts.googleapis.com.
 * In a shed with no signal both fail and the operator gets a blank, unstyled
 * screen. `support.js:1840` early-returns from loadReactUmd() when window.React
 * already exists, so loading our own copy first takes over cleanly with no edit
 * to the generated runtime.
 *
 * Everything written here IS committed — node_modules is not deployed.
 */
import { mkdir, copyFile, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const NM = path.join(ROOT, 'node_modules');
const p = (...s) => path.join(ROOT, ...s);

const INTER_WEIGHTS = [400, 500, 600, 700, 800];
const MONO_WEIGHTS = [500, 600];

async function ensure(dir) { await mkdir(dir, { recursive: true }); }

async function vendorScripts() {
  await ensure(p('vendor'));
  const jobs = [
    ['react/umd/react.production.min.js', 'vendor/react.production.min.js'],
    ['react-dom/umd/react-dom.production.min.js', 'vendor/react-dom.production.min.js'],
    ['@supabase/supabase-js/dist/umd/supabase.js', 'vendor/supabase.js']
  ];
  for (const [from, to] of jobs) {
    const src = path.join(NM, from);
    if (!existsSync(src)) throw new Error(`missing dependency: ${from} (run npm install)`);
    await copyFile(src, p(to));
    console.log(`  vendor  ${to}`);
  }
}

async function vendorFonts() {
  await ensure(p('fonts'));
  const faces = [];

  for (const w of INTER_WEIGHTS) {
    const file = `inter-latin-${w}-normal.woff2`;
    await copyFile(path.join(NM, '@fontsource/inter/files', file), p('fonts', file));
    faces.push({ family: 'Inter', weight: w, file });
  }
  for (const w of MONO_WEIGHTS) {
    const file = `ibm-plex-mono-latin-${w}-normal.woff2`;
    await copyFile(path.join(NM, '@fontsource/ibm-plex-mono/files', file), p('fonts', file));
    faces.push({ family: 'IBM Plex Mono', weight: w, file });
  }

  // font-display:swap so a cold cache still renders text immediately.
  const css = [
    '/* GENERATED by tools/vendor.mjs — do not edit. Self-hosted so the app',
    '   renders with no network. */',
    ...faces.map(f => [
      '@font-face{',
      `font-family:'${f.family}';`,
      'font-style:normal;',
      `font-weight:${f.weight};`,
      'font-display:swap;',
      `src:url('./${f.file}') format('woff2');`,
      'unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD;',
      '}'
    ].join(''))
  ].join('\n') + '\n';

  await writeFile(p('fonts', 'fonts.css'), css, 'utf8');
  console.log(`  fonts   ${faces.length} faces + fonts.css`);
}

/**
 * PWA icons. Rendered from SVG rather than upscaled from img/logo.png (48px),
 * which would be visibly blurry at 512.
 *
 * The maskable variant keeps the mark inside the safe zone (80% of the canvas)
 * because Android crops maskable icons to arbitrary shapes; without the padding
 * the wordmark loses its edges on circular-icon launchers.
 */
function iconSvg({ size, maskable }) {
  const pad = maskable ? size * 0.1 : 0;
  const box = size - pad * 2;
  const radius = maskable ? box * 0.18 : size * 0.18;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}" fill="#0A0A0A"/>
  <rect x="${pad}" y="${pad}" width="${box}" height="${box}" rx="${radius}" fill="#22C55E"/>
  <text x="${size / 2}" y="${size / 2}" fill="#061308"
        font-family="Helvetica,Arial,sans-serif" font-size="${box * 0.42}" font-weight="bold"
        text-anchor="middle" dominant-baseline="central">TE</text>
</svg>`;
}

async function buildIcons() {
  await ensure(p('img'));
  const targets = [
    { size: 192, maskable: false, out: 'img/icon-192.png' },
    { size: 512, maskable: false, out: 'img/icon-512.png' },
    { size: 512, maskable: true, out: 'img/icon-maskable-512.png' },
    // iOS home-screen icon. Installing to the home screen is what makes
    // navigator.storage.persist() stick on iOS, so this is load-bearing for
    // offline durability, not decoration.
    { size: 180, maskable: false, out: 'img/apple-touch-icon.png' }
  ];
  for (const t of targets) {
    const buf = Buffer.from(iconSvg(t));
    await sharp(buf).png({ compressionLevel: 9 }).toFile(p(t.out));
    console.log(`  icon    ${t.out}`);
  }
  await writeFile(p('img', 'icon.svg'), iconSvg({ size: 512, maskable: false }), 'utf8');
}

async function main() {
  console.log('vendoring offline assets...');
  await rm(p('vendor'), { recursive: true, force: true });
  await vendorScripts();
  await vendorFonts();
  await buildIcons();
  console.log('done.');
}

main().catch(e => { console.error('vendor failed:', e.message); process.exitCode = 1; });
